
#' Generate Record Linkage Pairs
#'
#' The `generate_pairs` function generates possible record linkage pairs between
#' two data frames using the RecordLinkage package. It computes the pairwise
#' similarity of records between two datasets and calculates weights for each
#' pair based on string similarity using the Levenshtein distance.
#'
#' @param df1 A data frame containing the first dataset to be compared.
#' @param df2 A data frame containing the second dataset to be compared.
#' @param exclude see RLBigDataLinkage
#' @param blockfld see RLBigDataLinkage
#'
#' @return A `RecLinkData` object with the computed pairwise comparison weights.
#'
#' @examples
#' # Example usage
#' df1 <- data.frame(name = c("John", "Jane"), age = c(25, 30))
#' df2 <- data.frame(name = c("Jon", "Janet"), age = c(26, 31))
#' pairs <- generate_pairs(df1, df2, excluded_cols = c("age"))
#'
#' @import RecordLinkage
#' @export

generate_pairs <- function (df1, df2, exclude = numeric(0), blockfld = list()) {

  # Find the pairs
  pairs <- RLBigDataLinkage(df1, df2, exclude = exclude, strcmp = TRUE,
                            blockfld = blockfld, strcmpfun = "levenshtein")

  # Calculate weights
  pairs_weighted <- epiWeights(pairs)

  return(pairs_weighted)
}

#' Classify Record Linkage Pairs
#'
#' The `classify_pairs` function classifies record linkage pairs into matches,
#' non-matches, and possible matches based on a lower and upper threshold for
#' linkage scores. It returns a list of paired records that are classified as
#' either links (matches) or possible links, along with the pairs for review.
#'
#' @param pairs A `RecLinkData` object, typically generated by the `generate_pairs` function,
#' containing pairwise comparison weights between two datasets.
#' @param lower_threshold A numeric value specifying the lower threshold for classification.
#' Pairs with weights below this threshold will not be considered matches. Default is 0.6.
#' @param upper_threshold A numeric value specifying the upper threshold for classification.
#' Pairs with weights above this threshold will be classified as matches. Default is 0.85.
#'
#' @return A list with two elements:
#' \item{pairs}{A data frame of record pairs classified as links or possible links.}
#' \item{review}{A data frame of the same pairs for manual review.}
#'
#' @examples
#' # Example usage
#' classified_pairs <- classify_pairs(pairs, lower_threshold = 0.6, upper_threshold = 0.85)
#'
#' @import RecordLinkage
#' @export

classify_pairs <- function(pairs, lower_threshold = 0.6,
                           upper_threshold = 0.85) {

  # Classify the links
  pairs_classified <- epiClassify(pairs, threshold.upper = upper_threshold,
                                  threshold.lower = lower_threshold)

  # Get pairs
  links <- getPairs(pairs_classified, filter.link = "link",
                    single.rows = TRUE)
  possible <- getPairs(pairs_classified, filter.link = "possible",
                       single.rows = TRUE)

  links_review <- getPairs(pairs_classified, filter.link = "link")
  possible_review <- getPairs(pairs_classified, filter.link = "possible")

  # Combine
  pairs <- rbind(links, possible)
  pairs_review <- rbind(links_review, possible_review)

  return(list(pairs = pairs, review = pairs_review))
}
